M48
; DRILL file KiCad 10.0.5 date 2026-08-20T13:54:44
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-20T13:54:44+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.700
%
G90
G05
T1
X77.11Y-42.4
X82.89Y-42.4
T2
X90.0Y-23.1
X90.0Y-24.9
T3
X76.5Y-34.0
X114.0Y-43.0
M30
