M48
; DRILL file KiCad 10.0.5 date 2026-08-20T12:22:00
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-20T12:22:00+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.700
%
G90
G05
T1
X3.4Y-7.11
X3.4Y-12.89
T2
X24.5Y-16.7
X24.5Y-18.5
T3
X13.5Y-2.1
X13.5Y-17.9
M30
