M48
; DRILL file KiCad 10.0.5 date 2026-08-20T15:23:36
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-20T15:23:36+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.700
%
G90
G05
T1
X79.11Y-46.4
X84.89Y-46.4
T2
X72.0Y-39.1
X72.0Y-40.9
T3
X70.0Y-33.5
X70.0Y-46.0
M30
