BOARD_ID = "board_a"; BOSS = True
WIFI_NETWORKS = [("TestNet", "pw")]
MQTT_BROKER = "test.local"; MQTT_PORT = 1883
MQTT_USER = ""; MQTT_PASSWORD = ""
MQTT_TOPIC_PREFIX = "test_prefix"
LED_PIN = 5; NUM_LEDS = 10; LED_BRIGHTNESS = 0.6; REVERSE_LEDS = False
TOUCH_PINS = [12]; TOUCH_THRESHOLD = 1; HOLD_TIME_MS = 3000
BASE_WARM_WHITE = (0, 0, 0, 200)
TINT_PALETTE = [(255,200,80),(255,0,0),(0,0,255),(0,220,0)]
NUM_GROUPS = 3; GROUP_MIN_LEDS = 1; GROUP_MAX_LEDS = 8
FADE_STEPS = 60; BREATHE_SPEED = 0.0008; BREATHE_DEPTH = 0.1
IDLE_DRIFT_INTERVAL_S = 65
WEBREPL_PASSWORD = "testpw"; RECONNECT_DELAY_MS = 5000
WATCHDOG_ENABLED = True
