M48
; DRILL file KiCad 10.0.5 date 2026-08-20T15:42:10
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-20T15:42:10+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.700
%
G90
G05
T1
X95.11Y-46.4
X100.89Y-46.4
T2
X84.0Y-22.6
X84.0Y-24.4
T3
X6.0Y-4.5
X126.0Y-26.5
X126.0Y-48.0
X181.0Y-4.5
M30
